### PR TITLE
Remove default.nix and link to external package

### PR DESCRIPTION
**Pull request by vdemeester**
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
Ah still there ? We can remove yes.

**Comment by vdemeester** [comment]
@chmouel yeah there is not nix gha anymore in the repository I think.

**Comment by 06kellyjac** [comment]
It should probably also mention nixpkgs too :)

**Comment by vdemeester** [comment]
> It should probably also mention nixpkgs too :)

What do you mean ? Is it packaged in nixpkgs ?

**Comment by vdemeester** [comment]
(If yes, I can remove it from my repo and rely only on upstream 🤭🤭🤭)

**Comment by vdemeester** [comment]
Oh yeah it is !! 🎉👏🏼 @06kellyjac

**Comment by chmouel** [comment]
@vdemeester would you like to change this to use nixpkgs then?

(and thanks @06kellyjac 🙏🏻 )

**Comment by vdemeester** [comment]
> @vdemeester would you like to change this to use nixpkgs then?
> 
> (and thanks @06kellyjac 🙏🏻 )

yes I will.

**Comment by vdemeester** [comment]
@chmouel https://github.com/chmouel/snazy/pull/233

**Pull request merged**
